#!/usr/bin/env bash

if
  [[ -s "/Users/arnabdey73/.rvm/gems/ruby-1.9.3-p551/environment" ]]
then
  source "/Users/arnabdey73/.rvm/gems/ruby-1.9.3-p551/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/arnabdey73/.rvm/gems/ruby-1.9.3-p551/environment'" >&2
  exit 1
fi
