#!/usr/bin/env bash

if
  [[ -s "/Users/arnabdey73/.rvm/gems/ruby-2.3.0@global/environment" ]]
then
  source "/Users/arnabdey73/.rvm/gems/ruby-2.3.0@global/environment"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/Users/arnabdey73/.rvm/gems/ruby-2.3.0@global/environment'" >&2
  exit 1
fi
